version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:

  build_and_unit_test:

    steps:
      - checkout
      - run:
          name: Running Unit Tests
          command: cd Authy; ./gradlew testAuthyAndroid4DebugUnitTest --no-daemon --max-workers 2


  ktlint_check:
    steps:
      - checkout
      - run:
          name: Running Ktlint
          command: cd Authy; ./gradlew ktlintCheck

workflows:
  workflow:
    jobs:
      - ktlint_check
      - build_and_unit_test:
          requires:
            - ktlint_check
