name: Generate Build

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: github.event.label.name == 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate Artifact
        run: ./gradlew artifactoryLibraryReleaseUpload
