name: Generate Build bak

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo comment
        run: echo ${{github.event.comment.body}}
